/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion.PAdministrarPrestamos;

import Negocio.NAdministrarLibros.LibroNegocio;
import Negocio.NAdministrarPrestamos.BibliotecarioNegocio;
import Negocio.NAdministrarPrestamos.FichaPrestamoNegocio;
import Negocio.NAdministrarPrestamos.LectorNegocio;

/**
 *
 * @author mauriballes
 */
public class FichaPrestamoFrm extends javax.swing.JFrame {

    /**
     * Creates new form FichaPrestamoFrm
     */
    private FichaPrestamoNegocio m_FichaPrestamoNegocio;
    private BibliotecarioNegocio m_BibliotecarioNegocio;
    private LectorNegocio m_LectorNegocio;
    private LibroNegocio m_LibroNegocio;

    public FichaPrestamoFrm() {
        initComponents();
        this.setTitle("Gestionar Ficha de Prestamo");
        this.setLocationRelativeTo(null);
        m_BibliotecarioNegocio = new BibliotecarioNegocio();
        m_LectorNegocio = new LectorNegocio();
        m_LibroNegocio = new LibroNegocio();
        m_FichaPrestamoNegocio = new FichaPrestamoNegocio();
        inicializar();
    }

    public void cargarComboEjemplares() {

    }

    public void cargarTablaBibliotecario() {

    }

    public void cargarTablaLector() {

    }

    public void cargarTablaLibro() {

    }

    public void concretarDevolucion() {

    }

    public void inicializar() {

    }

    public void obtenerDetallePrestamo() {

    }

    public void obtenerPrestamos() {

    }

    public void registrarPrestamo() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelFechaPrestamo = new javax.swing.JLabel();
        textFechaPrestamo = new javax.swing.JTextField();
        textFechaPrestamo1 = new javax.swing.JTextField();
        labelFechaDevolucion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableLibros = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableLectores = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableBibliotecario = new javax.swing.JTable();
        labelLectores = new javax.swing.JLabel();
        labelLibros = new javax.swing.JLabel();
        labelBibliotecario = new javax.swing.JLabel();
        labelEjemplar = new javax.swing.JLabel();
        comboEjemplar = new javax.swing.JComboBox<>();
        buttonAgregarEjemplar = new javax.swing.JButton();
        buttonRegistrar = new javax.swing.JButton();
        buttonObtener = new javax.swing.JButton();
        buttonConcretar = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablePrestamos = new javax.swing.JTable();
        labelPrestamos = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tableDetallePrestamos = new javax.swing.JTable();
        labelDetallePrestamos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelFechaPrestamo.setText("Fecha de Prestamo");

        labelFechaDevolucion.setText("Fecha de Devolucion");

        tableLibros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Id", "Titulo"
            }
        ));
        jScrollPane1.setViewportView(tableLibros);

        tableLectores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Id", "Apellidos y Nombres"
            }
        ));
        jScrollPane2.setViewportView(tableLectores);

        tableBibliotecario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Id", "Apellidos y Nombres"
            }
        ));
        jScrollPane3.setViewportView(tableBibliotecario);

        labelLectores.setText("Lectores");

        labelLibros.setText("Libros");

        labelBibliotecario.setText("Bibliotecario");

        labelEjemplar.setText("Ejemplar");

        comboEjemplar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        buttonAgregarEjemplar.setText("Agregar");

        buttonRegistrar.setText("Registrar Prestamo");

        buttonObtener.setText("Obtener Detalle");

        buttonConcretar.setText("Concretar Devolucion");

        tablePrestamos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Fecha Prestamo", "Fecha Devolucion", "Lector"
            }
        ));
        jScrollPane4.setViewportView(tablePrestamos);

        labelPrestamos.setText("Prestamos");

        tableDetallePrestamos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Libro", "Nro Ejemplar"
            }
        ));
        jScrollPane5.setViewportView(tableDetallePrestamos);

        labelDetallePrestamos.setText("Detalle Prestamos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(labelLectores)
                .addGap(214, 214, 214)
                .addComponent(labelLibros)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelBibliotecario)
                .addGap(97, 97, 97))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(379, 379, 379)
                        .addComponent(labelPrestamos))
                    .addComponent(jScrollPane4)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(labelFechaPrestamo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textFechaPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelFechaDevolucion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textFechaPrestamo1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                            .addComponent(buttonRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(buttonObtener, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(labelEjemplar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(comboEjemplar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(buttonAgregarEjemplar))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonConcretar, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane5))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(355, 355, 355)
                .addComponent(labelDetallePrestamos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFechaPrestamo)
                    .addComponent(textFechaPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelFechaDevolucion)
                    .addComponent(textFechaPrestamo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLectores)
                    .addComponent(labelLibros)
                    .addComponent(labelBibliotecario))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEjemplar)
                    .addComponent(comboEjemplar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonAgregarEjemplar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonConcretar)
                    .addComponent(buttonObtener)
                    .addComponent(buttonRegistrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelPrestamos)
                .addGap(2, 2, 2)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(labelDetallePrestamos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FichaPrestamoFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FichaPrestamoFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FichaPrestamoFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FichaPrestamoFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FichaPrestamoFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAgregarEjemplar;
    private javax.swing.JButton buttonConcretar;
    private javax.swing.JButton buttonObtener;
    private javax.swing.JButton buttonRegistrar;
    private javax.swing.JComboBox<String> comboEjemplar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel labelBibliotecario;
    private javax.swing.JLabel labelDetallePrestamos;
    private javax.swing.JLabel labelEjemplar;
    private javax.swing.JLabel labelFechaDevolucion;
    private javax.swing.JLabel labelFechaPrestamo;
    private javax.swing.JLabel labelLectores;
    private javax.swing.JLabel labelLibros;
    private javax.swing.JLabel labelPrestamos;
    private javax.swing.JTable tableBibliotecario;
    private javax.swing.JTable tableDetallePrestamos;
    private javax.swing.JTable tableLectores;
    private javax.swing.JTable tableLibros;
    private javax.swing.JTable tablePrestamos;
    private javax.swing.JTextField textFechaPrestamo;
    private javax.swing.JTextField textFechaPrestamo1;
    // End of variables declaration//GEN-END:variables
}
